version: '3'
services:
  app:
    build: ./
    ports:
      - '19090:19090'
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app
    ports:
      - '9090:9090'
