# See https://github.com/open-telemetry/opentelemetry-configuration for details on schema and examples
file_format: "0.1"

resource:
  attributes:
    service.name:  "file-configuration-example"

tracer_provider:
  processors:
    - batch:
        exporter:
          console: {}
  sampler:
    parent_based:
      root:
        rule_based_routing_sampler:
          fallback: always_on
          span_kind: SERVER
          drop_rules:
            - attribute: http.target
              pattern: "/actuator.*"
            - attribute: http.target
              pattern: "/foo"

propagators: [tracecontext, baggage]
