version: '3'
services:
  app:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "agent-example-app"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://collector:4318/v1/traces"
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://collector:4318/v1/metrics"
      OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: "http://collector:4318/v1/logs"
      # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
      # Optional specify file configuration instead of using environment variable scheme
      # To use, call "export OTEL_EXPERIMENTAL_CONFIG_FILE=/sdk-migration-config.yaml" before calling docker compose up
      OTEL_EXPERIMENTAL_CONFIG_FILE: /sdk-migration-config.yaml
    ports:
      - "8080:8080"
    volumes:
      - ./sdk-migration-config.yaml:/sdk-migration-config.yaml
    depends_on:
      - collector
  collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    volumes:
      - ./collector-config.yaml:/collector-config.yaml
    command: ["--config=/collector-config.yaml"]
    expose:
      - "4318"
    ports:
      - "4318:4318"
