file_format: "0.1"

resource:
  attributes:
    - name: service.name
      value: agent-example-app

logger_provider:
  processors:
    - batch:
        exporter:
          otlp:
            endpoint: http://collector:4318/v1/logs
            protocol: http/protobuf

tracer_provider:
  processors:
    - batch:
        exporter:
          otlp:
            endpoint: http://collector:4318/v1/traces
            protocol: http/protobuf

meter_provider:
  readers:
    - periodic:
        interval: 5000
        exporter:
          otlp:
            endpoint: http://collector:4318/v1/metrics
            protocol: http/protobuf
  # Example of how to use view to drop a metric which isn't needed.
  # This configuration is not available with the environment variable configuration scheme.
  # NOTE: most users will want jvm.memory.limit metric and should remove this view.
  views:
    - selector:
        instrument_name: jvm.memory.limit
      stream:
        aggregation:
          drop:

instrumentation:
  java:
    common:
      default-enabled: true
    methods:
      enabled: true
    external-annotations:
      enabled: true
    akka-actor:
      enabled: true
    akka-http:
      enabled: true
    axis2:
      enabled: true
    camel:
      enabled: true
    cassandra:
      enabled: true
    cxf:
      enabled: true
    apache-dbcp:
      enabled: true
    apache-dubbo:
      enabled: true
    geode:
      enabled: true
    apache-httpasyncclient:
      enabled: true
    apache-httpclient:
      enabled: true
    kafka:
      enabled: true
    jsf-myfaces:
      enabled: true
    pekko-actor:
      enabled: true
    pekko-http:
      enabled: true
    pulsar:
      enabled: true
    rocketmq-client:
      enabled: true
    apache-shenyu:
      enabled: true
    struts:
      enabled: true
    tapestry:
      enabled: true
    tomcat:
      enabled: true
    wicket:
      enabled: true
    armeria:
      enabled: true
    async-http-client:
      enabled: true
    aws-lambda:
      enabled: true
    aws-sdk:
      enabled: true
    azure-core:
      enabled: true
    clickhouse:
      enabled: true
    couchbase:
      enabled: true
    c3p0:
      enabled: true
    dropwizard-views:
      enabled: true
    dropwizard-metrics:
      enabled: true
    grizzly:
      enabled: true
    jersey:
      enabled: true
    jetty:
      enabled: true
    jetty-httpclient:
      enabled: true
    metro:
      enabled: true
    jsf-mojarra:
      enabled: true
    vertx-http-client:
      enabled: true
    vertx-kafka-client:
      enabled: true
    vertx-redis-client:
      enabled: true
    vertx-rx-java:
      enabled: true
    vertx-sql-client:
      enabled: true
    vertx-web:
      enabled: true
    elasticsearch-transport:
      enabled: true
    elasticsearch-rest:
      enabled: true
    finagle-http:
      enabled: true
    guava:
      enabled: true
    google-http-client:
      enabled: true
    gwt:
      enabled: true
    grails:
      enabled: true
    graphql-java:
      enabled: true
    grpc:
      enabled: true
    hibernate:
      enabled: true
    hibernate-reactive:
      enabled: true
    hikaricp:
      enabled: true
    influxdb:
      enabled: true
    java-http-client:
      enabled: true
    http-url-connection:
      enabled: true
    jdbc:
      enabled: true
    jdbc-datasource:
      enabled: true
    rmi:
      enabled: true
    runtime-telemetry:
      enabled: false
    servlet:
      enabled: true
    executors:
      enabled: true
    java-util-logging:
      enabled: true
    javalin:
      enabled: true
    jaxrs-client:
      enabled: true
    jaxrs:
      enabled: true
    jaxws:
      enabled: true
    jboss-logmanager-appender:
      enabled: true
    jboss-logmanager-mdc:
      enabled: true
    jms:
      enabled: true
    jodd-http:
      enabled: true
    jsp:
      enabled: true
    kubernetes-client:
      enabled: true
    ktor:
      enabled: true
    kotlinx-coroutines:
      enabled: true
    log4j-appender:
      enabled: true
    log4j-mdc:
      enabled: true
    log4j-context-data:
      enabled: true
    logback-appender:
      enabled: true
    logback-mdc:
      enabled: true
    micrometer:
      enabled: true
    mongo:
      enabled: true
    mybatis:
      enabled: true
    hystrix:
      enabled: true
    netty:
      enabled: true
    okhttp:
      enabled: true
    liberty:
      enabled: true
    opentelemetry-extension-annotations:
      enabled: true
    opentelemetry-instrumentation-annotations:
      enabled: true
    opentelemetry-api:
      enabled: true
    oracle-ucp:
      enabled: true
    oshi:
      enabled: true
    play:
      enabled: true
    play-ws:
      enabled: true
    quarkus:
      enabled: true
    quartz:
      enabled: true
    r2dbc:
      enabled: true
    rabbitmq:
      enabled: true
    ratpack:
      enabled: true
    rxjava:
      enabled: true
    reactor:
      enabled: true
    reactor-kafka:
      enabled: true
    reactor-netty:
      enabled: true
    jedis:
      enabled: true
    lettuce:
      enabled: true
    rediscala:
      enabled: true
    redisson:
      enabled: true
    restlet:
      enabled: true
    scala-fork-join:
      enabled: true
    spark:
      enabled: true
    spring-batch:
      enabled: true
    spring-core:
      enabled: true
    spring-data:
      enabled: true
    spring-jms:
      enabled: true
    spring-integration:
      enabled: true
    spring-kafka:
      enabled: true
    spring-rabbit:
      enabled: true
    spring-rmi:
      enabled: true
    spring-scheduling:
      enabled: true
    spring-web:
      enabled: true
    spring-webflux:
      enabled: true
    spring-webmvc:
      enabled: true
    spring-ws:
      enabled: true
    spymemcached:
      enabled: true
    tomcat-jdbc:
      enabled: true
    twilio:
      enabled: true
    finatra:
      enabled: true
    undertow:
      enabled: true
    vaadin:
      enabled: true
    vibur-dbcp:
      enabled: true
    xxl-job:
      enabled: true
    zio:
      enabled: true
