file_format: "0.1"

resource:
  attributes:
    service.name: agent-example-app

logger_provider:
  processors:
    - batch:
        exporter:
          otlp:
            endpoint: http://collector:4317

tracer_provider:
  processors:
    - batch:
        exporter:
          otlp:
            endpoint: http://collector:4317

meter_provider:
  readers:
    - periodic:
        exporter:
          otlp:
            endpoint: http://collector:4317
  # Example of how to use view to drop a metric which isn't needed.
  # This configuration is not available with the environment variable configuration scheme.
  # NOTE: most users will want jvm.memory.limit metric and should remove this view.
  views:
    - selector:
        instrument_name: jvm.memory.limit
      stream:
        aggregation:
          drop:
